export const userConstants = {
    SIGNUP_REQUEST: 'USERS_SIGNUP_REQUEST',
    SIGNUP_SUCCESS: 'USERS_SIGNUP_SUCCESS',
    SIGNUP_FAILURE: 'USERS_SIGNUP_FAILURE',

    LOGIN_REQUEST: 'USERS_LOGIN_REQUEST',
    LOGIN_SUCCESS: 'USERS_LOGIN_SUCCESS',
    LOGIN_FAILURE: 'USERS_LOGIN_FAILURE',

    FILEUPLOAD_SUCCESS: 'USERS_FILEUPLOAD_SUCCESS',
    FILEUPLOAD_FAILURE: 'USERS_FILEUPLOAD_FAILURE',


    GETALLFILES_REQUEST: 'FILES_GETALL_REQUEST',
    GETALLFILES_SUCCESS: 'FILES_GETALL_SUCCESS',
    GETALLFILES_FAILURE: 'FILES_GETALL_FAILURE',

    TOGGLE_STAR: 'TOGGLE_STAR_SUCCESS',
    DELETE_FILE: 'DELETE_FILE_SUCCESS',

    CREATE_FOLDER: 'CREATE_FOLDER_SUCCESS',
    
    LOGOUT: 'USERS_LOGOUT'  
};
